os: linux
dist: bionic
language: php

env:
  global:
    - COMPOSER_FLAGS="--ansi --no-interaction --no-progress --no-suggest --prefer-dist"
    - COMPOSER_UPDATE_FLAGS=""
    - PHPUNIT_FLAGS=""
    - REPORT_COVERAGE=false
    - SYMFONY_PHPUNIT_VERSION=8.5
    - SYMFONY_PHPUNIT_REMOVE_RETURN_TYPEHINT=1

matrix:
  include:
    - php: 5.3
      dist: precise
      env:
        - SYMFONY_PHPUNIT_VERSION=4.8
    - php: 5.4
      dist: trusty
      env:
        - SYMFONY_PHPUNIT_VERSION=4.8
    - php: 5.5
      dist: trusty
      env:
        - SYMFONY_PHPUNIT_VERSION=4.8
    - php: 5.6
      dist: trusty
      env:
        - SYMFONY_PHPUNIT_VERSION=5.7
    - php: 7.0
      dist: xenial
      env:
        - SYMFONY_PHPUNIT_VERSION=6.5
    - php: 7.1
      env:
        - SYMFONY_PHPUNIT_VERSION=7.5
    - php: 7.2
    - php: 7.3
    - php: 7.3
      env:
        - COMPOSER_LATEST=true
    - php: 7.4
      env:
        - PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"
        - REPORT_COVERAGE=true
    - php: 8.0
      env:
        - SYMFONY_PHPUNIT_VERSION=9.5
    - php: 8.1
      env:
        - COMPOSER_LATEST=true
        - SYMFONY_PHPUNIT_VERSION=9.5
    - php: nightly
      env:
        - COMPOSER_LATEST=true
        - SYMFONY_PHPUNIT_VERSION=9.5
  fast_finish: true
  allow_failures:
    - php: 5.3
    - php: nightly

branches:
  only:
    - main

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  # In September 2021, the Let's encrypt root authority certificate expired,
  # which invalidates Composer's certificates.
  - if [[ $TRAVIS_DIST == 'precise' ]]; then
      wget https://curl.se/ca/cacert.pem -O /tmp/cacert.pem --no-check-certificate;
      echo "openssl.cafile=/tmp/cacert.pem" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
    fi
  # Update Composer to the latest supported version
  - composer self-update

install:
  # Remove platform config to get latest dependencies or current PHP version
  - composer config platform --unset
  # Update dependencies from composer.json using composer binary provided by system
  - composer update $COMPOSER_UPDATE_FLAGS $COMPOSER_FLAGS
  # Install snapshot of Composer
  - if [[ $COMPOSER_LATEST == 'true' ]]; then composer require composer/composer:^2.0 --dev --prefer-stable --update-with-dependencies; fi
  # Require latest PHPUnitBridge for PHP 8
  - if [[ $TRAVIS_PHP_VERSION == 'nightly' ]]; then composer require --no-update --dev symfony/phpunit-bridge:^6.0; fi
  # Update Symfony's PHPUnitBridge to latest available for the current PHP always as it is not really a dependency of the project
  - composer update $COMPOSER_FLAGS symfony/phpunit-bridge
  # Install dependencies
  - composer install $COMPOSER_FLAGS

script:
  - ./vendor/bin/simple-phpunit $PHPUNIT_FLAGS

after_script:
  - if [[ $REPORT_COVERAGE ]]; then composer require php-coveralls/php-coveralls; fi
  - if [[ $REPORT_COVERAGE ]]; then php vendor/bin/php-coveralls -v; fi
