os: linux
dist: bionic
language: php

env:
  global:
    - COMPOSER_FLAGS="--ansi --no-interaction --no-progress --no-suggest --prefer-dist"
    - COMPOSER_UPDATE_FLAGS=""
    - PHPUNIT_FLAGS=""
    - REPORT_COVERAGE=false
    - SYMFONY_PHPUNIT_VERSION=8.5

matrix:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4
      env:
        - PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"
        - REPORT_COVERAGE=true
    - php: 8.0
      env:
        - SYMFONY_PHPUNIT_VERSION=9.5
    - php: 8.1
      env:
        - SYMFONY_PHPUNIT_VERSION=9.5
    - php: nightly
      env:
        - SYMFONY_PHPUNIT_VERSION=9.5
  fast_finish: true
  allow_failures:
    - php: nightly

branches:
  only:
    - main

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  # Update Composer to the latest supported version
  - composer self-update

install:
  # Remove platform config to get latest dependencies or current PHP version
  - composer config platform --unset
  # Update dependencies from composer.json using composer binary provided by system
  - composer update $COMPOSER_UPDATE_FLAGS $COMPOSER_FLAGS
  # Install dependencies
  - composer install $COMPOSER_FLAGS

script:
  - ./vendor/bin/simple-phpunit $PHPUNIT_FLAGS

after_script:
  - if [[ $REPORT_COVERAGE ]]; then
      composer require php-coveralls/php-coveralls;
      php vendor/bin/php-coveralls -v;
    fi
